# Generated by Django 4.0.1 on 2022-02-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_header_replytocomment_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='replytocomment',
            name='dislike',
            field=models.BooleanField(default=False, verbose_name='Дизлайк'),
        ),
        migrations.AddField(
            model_name='replytocomment',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Лайк'),
        ),
    ]
